use anyhow::Result;
use colored::Colorize;
use std::process::Command;

use crate::config::Config;
use crate::manifest::Manifest;

/// Generate Caddy configuration for a project
pub fn generate_config(project_name: &str, manifest: &Manifest) -> Result<()> {
    let config = Config::load()?;

    // Ensure sites.d directory exists
    std::fs::create_dir_all(&config.caddy_sites_dir)?;

    let config_path = config
        .caddy_sites_dir
        .join(format!("{}.caddy", project_name));

    let mut content = format!("# {} - Auto-generated by DevHub\n", project_name);
    content.push_str(&format!(
        "# Generated: {}\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));
    content.push('\n');

    for service in &manifest.services {
        let hostname = if service.main {
            format!("{}.localhost", project_name)
        } else {
            let subdomain = service.subdomain.as_ref().unwrap_or(&service.name);
            format!("{}.{}.localhost", subdomain, project_name)
        };

        content.push_str(&format!("http://{} {{\n", hostname));
        content.push_str(&format!(
            "    reverse_proxy host.docker.internal:{}\n",
            service.port
        ));
        content.push_str("}\n\n");
    }

    std::fs::write(&config_path, &content)?;

    tracing::info!("Generated Caddy config at {}", config_path.display());

    println!(
        "  {} Caddy config generated: {}",
        "✓".green(),
        config_path.display().to_string().dimmed()
    );

    Ok(())
}

/// Remove Caddy configuration for a project
pub fn remove_config(project_name: &str) -> Result<()> {
    let config = Config::load()?;
    let config_path = config
        .caddy_sites_dir
        .join(format!("{}.caddy", project_name));

    if config_path.exists() {
        std::fs::remove_file(&config_path)?;
        tracing::info!("Removed Caddy config at {}", config_path.display());
    }

    Ok(())
}

/// Reload Caddy to pick up configuration changes
pub fn reload() -> Result<()> {
    let config = Config::load()?;

    // Parse the reload command
    let parts: Vec<&str> = config.caddy_reload_command.split_whitespace().collect();
    if parts.is_empty() {
        return Ok(());
    }

    let output = Command::new(parts[0]).args(&parts[1..]).output();

    match output {
        Ok(out) if out.status.success() => {
            println!("  {} Caddy reloaded", "✓".green());
        }
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            if !stderr.is_empty() {
                tracing::warn!("Caddy reload warning: {}", stderr);
            }
            println!("  {} Caddy reload may have failed", "!".yellow());
        }
        Err(e) => {
            tracing::warn!("Could not reload Caddy: {}", e);
            println!(
                "  {} Caddy not running or not accessible ({})",
                "!".yellow(),
                "run manually if needed".dimmed()
            );
        }
    }

    Ok(())
}

/// Check if Caddy proxy is running
pub fn is_caddy_running() -> bool {
    let output = Command::new("docker")
        .args([
            "ps",
            "--filter",
            "name=caddy-proxy",
            "--format",
            "{{.Names}}",
        ])
        .output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            stdout.contains("caddy-proxy")
        }
        Err(_) => false,
    }
}
