//! Caddy reverse proxy configuration generation.
//!
//! This module generates Caddy configuration files for routing traffic
//! to project services. It supports both native mode (routing to host ports)
//! and container mode (routing to container names via Docker networks).

use anyhow::Result;
use colored::Colorize;
use std::process::Command;

use crate::config::Config;
use crate::docker;
use crate::manifest::{Manifest, ProjectMode, Service, ServiceMode};

/// Generate Caddy configuration for a project
pub fn generate_config(project_name: &str, manifest: &Manifest) -> Result<()> {
    let config = Config::load()?;

    // Ensure sites.d directory exists
    std::fs::create_dir_all(&config.caddy_sites_dir)?;

    let config_path = config
        .caddy_sites_dir
        .join(format!("{}.caddy", project_name));

    let mut content = format!("# {} - Auto-generated by DevHub\n", project_name);
    content.push_str(&format!("# Mode: {}\n", manifest.project.mode));
    content.push_str(&format!(
        "# Generated: {}\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));
    content.push('\n');

    for service in &manifest.services {
        let hostname = build_hostname(project_name, service);
        let upstream = build_upstream(project_name, service, &manifest.project.mode);

        content.push_str(&format!("http://{} {{\n", hostname));
        content.push_str(&format!("    reverse_proxy {}\n", upstream));
        content.push_str("}\n\n");
    }

    std::fs::write(&config_path, &content)?;

    tracing::info!("Generated Caddy config at {}", config_path.display());

    println!(
        "  {} Caddy config generated: {}",
        "✓".green(),
        config_path.display().to_string().dimmed()
    );

    Ok(())
}

/// Build the hostname for a service
fn build_hostname(project_name: &str, service: &Service) -> String {
    if service.main {
        format!("{}.localhost", project_name)
    } else {
        let subdomain = service.subdomain.as_ref().unwrap_or(&service.name);
        format!("{}.{}.localhost", subdomain, project_name)
    }
}

/// Build the upstream address based on service mode
///
/// For native mode: routes to host.docker.internal:{port}
/// For container mode: routes to container name (e.g., project-api:8080)
fn build_upstream(project_name: &str, service: &Service, project_mode: &ProjectMode) -> String {
    let effective_mode = get_effective_mode(service, project_mode);

    match effective_mode {
        ProjectMode::Container => {
            // Route to container name via Docker network DNS
            let container = docker::container_name(project_name, &service.name);
            let port = service.internal_port.unwrap_or(service.port);
            format!("{}:{}", container, port)
        }
        ProjectMode::Native | ProjectMode::Hybrid => {
            // Route to host machine (for native and hybrid-native services)
            format!("host.docker.internal:{}", service.port)
        }
    }
}

/// Get the effective mode for a service
fn get_effective_mode(service: &Service, project_mode: &ProjectMode) -> ProjectMode {
    match (&service.mode, project_mode) {
        // Service-level override takes precedence
        (Some(ServiceMode::Container), _) => ProjectMode::Container,
        (Some(ServiceMode::Native), _) => ProjectMode::Native,

        // Hybrid mode - check per-service override, default to native
        (None, ProjectMode::Hybrid) => ProjectMode::Native,

        // Otherwise use project mode
        (None, mode) => mode.clone(),
    }
}

/// Remove Caddy configuration for a project
#[allow(dead_code)]
pub fn remove_config(project_name: &str) -> Result<()> {
    let config = Config::load()?;
    let config_path = config
        .caddy_sites_dir
        .join(format!("{}.caddy", project_name));

    if config_path.exists() {
        std::fs::remove_file(&config_path)?;
        tracing::info!("Removed Caddy config at {}", config_path.display());
    }

    Ok(())
}

/// Reload Caddy to pick up configuration changes
pub fn reload() -> Result<()> {
    let config = Config::load()?;

    // Parse the reload command
    let parts: Vec<&str> = config.caddy_reload_command.split_whitespace().collect();
    if parts.is_empty() {
        return Ok(());
    }

    let output = Command::new(parts[0]).args(&parts[1..]).output();

    match output {
        Ok(out) if out.status.success() => {
            println!("  {} Caddy reloaded", "✓".green());
        }
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            if !stderr.is_empty() {
                tracing::warn!("Caddy reload warning: {}", stderr);
            }
            println!("  {} Caddy reload may have failed", "!".yellow());
        }
        Err(e) => {
            tracing::warn!("Could not reload Caddy: {}", e);
            println!(
                "  {} Caddy not running or not accessible ({})",
                "!".yellow(),
                "run manually if needed".dimmed()
            );
        }
    }

    Ok(())
}

/// Check if Caddy proxy is running
#[allow(dead_code)]
pub fn is_caddy_running() -> bool {
    let output = Command::new("docker")
        .args([
            "ps",
            "--filter",
            "name=caddy-proxy",
            "--format",
            "{{.Names}}",
        ])
        .output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            stdout.contains("caddy-proxy")
        }
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::ServiceType;
    use std::collections::HashMap;

    fn make_test_service(name: &str, port: u16, main: bool) -> Service {
        Service {
            name: name.to_string(),
            service_type: ServiceType::Node,
            command: "npm start".to_string(),
            port,
            cwd: None,
            health_check: None,
            subdomain: None,
            main,
            depends_on: vec![],
            env: HashMap::new(),
            env_file: None,
            mode: None,
            image: None,
            dockerfile: None,
            build_context: None,
            internal_port: None,
            networks: vec![],
            volumes: vec![],
        }
    }

    #[test]
    fn test_build_hostname_main_service() {
        let service = make_test_service("web", 3000, true);
        assert_eq!(build_hostname("myproject", &service), "myproject.localhost");
    }

    #[test]
    fn test_build_hostname_subdomain_service() {
        let mut service = make_test_service("api", 8080, false);
        service.subdomain = Some("api".to_string());
        assert_eq!(
            build_hostname("myproject", &service),
            "api.myproject.localhost"
        );
    }

    #[test]
    fn test_build_hostname_auto_subdomain() {
        let service = make_test_service("backend", 8080, false);
        // No subdomain set, should use service name
        assert_eq!(
            build_hostname("myproject", &service),
            "backend.myproject.localhost"
        );
    }

    #[test]
    fn test_build_upstream_native_mode() {
        let service = make_test_service("api", 8080, false);

        let upstream = build_upstream("myproject", &service, &ProjectMode::Native);
        assert_eq!(upstream, "host.docker.internal:8080");
    }

    #[test]
    fn test_build_upstream_container_mode() {
        let service = make_test_service("api", 8080, false);

        let upstream = build_upstream("myproject", &service, &ProjectMode::Container);
        assert_eq!(upstream, "myproject-api:8080");
    }

    #[test]
    fn test_build_upstream_container_mode_with_internal_port() {
        let mut service = make_test_service("api", 8080, false);
        service.internal_port = Some(3000);

        let upstream = build_upstream("myproject", &service, &ProjectMode::Container);
        assert_eq!(upstream, "myproject-api:3000");
    }

    #[test]
    fn test_build_upstream_service_mode_override() {
        let mut service = make_test_service("api", 8080, false);
        service.mode = Some(ServiceMode::Native);

        // Even with project in container mode, service should be native
        let upstream = build_upstream("myproject", &service, &ProjectMode::Container);
        assert_eq!(upstream, "host.docker.internal:8080");
    }

    #[test]
    fn test_effective_mode_service_override() {
        let mut service = make_test_service("api", 8080, false);
        service.mode = Some(ServiceMode::Container);

        // Service override to container when project is native
        assert_eq!(
            get_effective_mode(&service, &ProjectMode::Native),
            ProjectMode::Container
        );
    }

    #[test]
    fn test_effective_mode_hybrid_defaults_native() {
        let service = make_test_service("api", 8080, false);

        // In hybrid mode without service override, default to native
        assert_eq!(
            get_effective_mode(&service, &ProjectMode::Hybrid),
            ProjectMode::Native
        );
    }
}
