//! Dockerfile generation for DevHub container mode.
//!
//! This module provides auto-generation of Dockerfiles for projects
//! that want to run in container mode but don't have their own Dockerfile.
//!
//! Note: This module is foundation code for CR-001 (Docker Network Isolation).
//! Functions are not yet wired into the main CLI but will be in a future release.

#![allow(dead_code)]

use anyhow::Result;
use std::path::Path;

use crate::manifest::{Manifest, Service, ServiceType};

/// Get the default base image for a service type
pub fn get_base_image(service_type: &ServiceType) -> &'static str {
    match service_type {
        ServiceType::Node => "node:22-alpine",
        ServiceType::Python => "python:3.12-slim",
        ServiceType::Go => "golang:1.22-alpine",
        ServiceType::Dart => "dart:3.5",
        ServiceType::RustBinary => "rust:1.75-alpine",
        ServiceType::DockerCompose => "alpine:latest",
        ServiceType::Shell => "alpine:latest",
    }
}

/// Generate a Dockerfile for a service
pub fn generate_dockerfile(service: &Service, manifest: &Manifest) -> String {
    // Use custom image if specified, otherwise use default for service type
    let base_image = service
        .image
        .as_deref()
        .unwrap_or_else(|| get_base_image(&service.service_type));

    match service.service_type {
        ServiceType::Node => generate_node_dockerfile(service, base_image),
        ServiceType::Python => generate_python_dockerfile(service, base_image),
        ServiceType::Go => generate_go_dockerfile(service, base_image),
        ServiceType::Dart => generate_dart_dockerfile(service, manifest, base_image),
        ServiceType::RustBinary => generate_rust_dockerfile(service, base_image),
        ServiceType::Shell => generate_shell_dockerfile(service, base_image),
        ServiceType::DockerCompose => {
            // Docker Compose services shouldn't need a Dockerfile from us
            String::new()
        }
    }
}

/// Generate a Dockerfile for Node.js services
fn generate_node_dockerfile(service: &Service, base_image: &str) -> String {
    let port = service.internal_port.unwrap_or(service.port);
    let workdir = service.cwd.as_deref().unwrap_or(".");

    format!(
        r#"# Auto-generated by DevHub for container mode
# Service: {name}
FROM {base_image}

WORKDIR /app/{workdir}

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production 2>/dev/null || npm install --production

# Copy source code
COPY . .

# Expose the internal port
EXPOSE {port}

# Start the service
CMD {command}
"#,
        name = service.name,
        base_image = base_image,
        workdir = workdir,
        port = port,
        command = format_command_for_docker(&service.command),
    )
}

/// Generate a Dockerfile for Python services
fn generate_python_dockerfile(service: &Service, base_image: &str) -> String {
    let port = service.internal_port.unwrap_or(service.port);
    let workdir = service.cwd.as_deref().unwrap_or(".");

    format!(
        r#"# Auto-generated by DevHub for container mode
# Service: {name}
FROM {base_image}

WORKDIR /app/{workdir}

# Install dependencies
COPY requirements*.txt pyproject.toml* ./
RUN pip install --no-cache-dir -r requirements.txt 2>/dev/null || \
    pip install --no-cache-dir -e . 2>/dev/null || \
    echo "No requirements found"

# Copy source code
COPY . .

# Expose the internal port
EXPOSE {port}

# Start the service
CMD {command}
"#,
        name = service.name,
        base_image = base_image,
        workdir = workdir,
        port = port,
        command = format_command_for_docker(&service.command),
    )
}

/// Generate a Dockerfile for Go services
fn generate_go_dockerfile(service: &Service, base_image: &str) -> String {
    let port = service.internal_port.unwrap_or(service.port);
    let workdir = service.cwd.as_deref().unwrap_or(".");

    format!(
        r#"# Auto-generated by DevHub for container mode
# Service: {name}
FROM {base_image} AS builder

WORKDIR /app/{workdir}

# Download dependencies
COPY go.mod go.sum* ./
RUN go mod download 2>/dev/null || true

# Copy source and build
COPY . .
RUN CGO_ENABLED=0 go build -o /app/service .

# Runtime stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/service .

# Expose the internal port
EXPOSE {port}

# Start the service
CMD ["./service"]
"#,
        name = service.name,
        base_image = base_image,
        workdir = workdir,
        port = port,
    )
}

/// Generate a Dockerfile for Dart services (including Serverpod)
fn generate_dart_dockerfile(service: &Service, manifest: &Manifest, base_image: &str) -> String {
    let port = service.internal_port.unwrap_or(service.port);
    let workdir = service.cwd.as_deref().unwrap_or(".");

    // Check if this looks like a Serverpod project
    let is_serverpod = service.command.contains("serverpod")
        || manifest.project.name.contains("serverpod")
        || service.name.contains("server");

    if is_serverpod {
        generate_serverpod_dockerfile(service, base_image, port, workdir)
    } else {
        format!(
            r#"# Auto-generated by DevHub for container mode
# Service: {name}
FROM {base_image}

WORKDIR /app/{workdir}

# Get dependencies
COPY pubspec.* ./
RUN dart pub get

# Copy source code
COPY . .

# Expose the internal port
EXPOSE {port}

# Start the service
CMD {command}
"#,
            name = service.name,
            base_image = base_image,
            workdir = workdir,
            port = port,
            command = format_command_for_docker(&service.command),
        )
    }
}

/// Generate a Dockerfile for Serverpod projects
fn generate_serverpod_dockerfile(
    service: &Service,
    base_image: &str,
    port: u16,
    workdir: &str,
) -> String {
    format!(
        r#"# Auto-generated by DevHub for container mode
# Service: {name} (Serverpod)
FROM {base_image}

WORKDIR /app/{workdir}

# Install serverpod_cli
RUN dart pub global activate serverpod_cli

# Get dependencies
COPY pubspec.* ./
RUN dart pub get

# Copy source code
COPY . .

# Generate code (if needed)
RUN dart pub get && \
    (serverpod generate 2>/dev/null || true)

# Build for production
RUN dart compile exe bin/main.dart -o bin/server

# Expose the internal port
EXPOSE {port}

# Start the service
CMD ["./bin/server", "--mode", "production"]
"#,
        name = service.name,
        base_image = base_image,
        workdir = workdir,
        port = port,
    )
}

/// Generate a Dockerfile for Rust services
fn generate_rust_dockerfile(service: &Service, base_image: &str) -> String {
    let port = service.internal_port.unwrap_or(service.port);
    let workdir = service.cwd.as_deref().unwrap_or(".");

    format!(
        r#"# Auto-generated by DevHub for container mode
# Service: {name}
FROM {base_image} AS builder

WORKDIR /app/{workdir}

# Create a dummy project to cache dependencies
RUN mkdir src && echo "fn main() {{}}" > src/main.rs
COPY Cargo.toml Cargo.lock* ./
RUN cargo build --release 2>/dev/null || true
RUN rm -rf src

# Copy real source and build
COPY . .
RUN cargo build --release

# Runtime stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates libgcc
WORKDIR /app
COPY --from=builder /app/target/release/* ./

# Expose the internal port
EXPOSE {port}

# Start the service
CMD {command}
"#,
        name = service.name,
        base_image = base_image,
        workdir = workdir,
        port = port,
        command = format_command_for_docker(&service.command),
    )
}

/// Generate a simple Dockerfile for shell services
fn generate_shell_dockerfile(service: &Service, base_image: &str) -> String {
    let port = service.internal_port.unwrap_or(service.port);
    let workdir = service.cwd.as_deref().unwrap_or(".");

    format!(
        r#"# Auto-generated by DevHub for container mode
# Service: {name}
FROM {base_image}

WORKDIR /app/{workdir}

# Install common utilities
RUN apk --no-cache add bash curl jq

# Copy source code
COPY . .

# Expose the internal port
EXPOSE {port}

# Start the service
CMD {command}
"#,
        name = service.name,
        base_image = base_image,
        workdir = workdir,
        port = port,
        command = format_command_for_docker(&service.command),
    )
}

/// Format a command string for Docker CMD instruction
fn format_command_for_docker(command: &str) -> String {
    // Split command into parts and format as JSON array
    let parts: Vec<&str> = command.split_whitespace().collect();
    let json_parts: Vec<String> = parts.iter().map(|p| format!("\"{}\"", p)).collect();
    format!("[{}]", json_parts.join(", "))
}

/// Check if a project has a Dockerfile for a service
pub fn has_dockerfile(project_path: &Path, service: &Service) -> bool {
    // Check for service-specific Dockerfile
    if let Some(ref dockerfile) = service.dockerfile {
        return project_path.join(dockerfile).exists();
    }

    // Check for standard Dockerfile locations
    let dockerfile_paths = [
        project_path.join("Dockerfile"),
        project_path
            .join(".devhub")
            .join(format!("Dockerfile.{}", service.name)),
    ];

    // If service has a cwd, also check there
    if let Some(ref cwd) = service.cwd {
        let service_dir = project_path.join(cwd);
        if service_dir.join("Dockerfile").exists() {
            return true;
        }
    }

    dockerfile_paths.iter().any(|p| p.exists())
}

/// Write a generated Dockerfile for a service
pub fn write_dockerfile(project_path: &Path, service: &Service, manifest: &Manifest) -> Result<()> {
    let devhub_dir = project_path.join(".devhub");
    std::fs::create_dir_all(&devhub_dir)?;

    let dockerfile_path = devhub_dir.join(format!("Dockerfile.{}", service.name));
    let content = generate_dockerfile(service, manifest);

    if content.is_empty() {
        return Ok(()); // Docker Compose services don't need a Dockerfile
    }

    std::fs::write(&dockerfile_path, content)?;
    tracing::info!(
        "Generated Dockerfile for service '{}' at {:?}",
        service.name,
        dockerfile_path
    );

    Ok(())
}

/// Generate Dockerfiles for all services in a project
pub fn generate_project_dockerfiles(project_path: &Path, manifest: &Manifest) -> Result<()> {
    for service in &manifest.services {
        // Skip if service already has a Dockerfile
        if has_dockerfile(project_path, service) {
            tracing::debug!(
                "Service '{}' already has a Dockerfile, skipping generation",
                service.name
            );
            continue;
        }

        // Skip Docker Compose services
        if service.service_type == ServiceType::DockerCompose {
            continue;
        }

        write_dockerfile(project_path, service, manifest)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn create_test_service(name: &str, service_type: ServiceType, command: &str) -> Service {
        Service {
            name: name.to_string(),
            service_type,
            command: command.to_string(),
            port: 8080,
            cwd: None,
            health_check: None,
            subdomain: None,
            main: false,
            depends_on: vec![],
            env: HashMap::new(),
            env_file: None,
            mode: None,
            image: None,
            dockerfile: None,
            build_context: None,
            internal_port: None,
            networks: vec![],
            volumes: vec![],
        }
    }

    fn create_test_manifest() -> Manifest {
        Manifest::template("test-project")
    }

    #[test]
    fn test_get_base_image() {
        assert_eq!(get_base_image(&ServiceType::Node), "node:22-alpine");
        assert_eq!(get_base_image(&ServiceType::Python), "python:3.12-slim");
        assert_eq!(get_base_image(&ServiceType::Dart), "dart:3.5");
        assert_eq!(get_base_image(&ServiceType::Go), "golang:1.22-alpine");
        assert_eq!(get_base_image(&ServiceType::RustBinary), "rust:1.75-alpine");
    }

    #[test]
    fn test_format_command_for_docker() {
        assert_eq!(
            format_command_for_docker("npm start"),
            "[\"npm\", \"start\"]"
        );
        assert_eq!(
            format_command_for_docker("dart run bin/server.dart"),
            "[\"dart\", \"run\", \"bin/server.dart\"]"
        );
    }

    #[test]
    fn test_generate_node_dockerfile() {
        let service = create_test_service("api", ServiceType::Node, "npm start");
        let manifest = create_test_manifest();
        let dockerfile = generate_dockerfile(&service, &manifest);

        assert!(dockerfile.contains("FROM node:22-alpine"));
        assert!(dockerfile.contains("EXPOSE 8080"));
        assert!(dockerfile.contains("npm ci"));
    }

    #[test]
    fn test_generate_dart_dockerfile() {
        let service = create_test_service("api", ServiceType::Dart, "dart run bin/server.dart");
        let manifest = create_test_manifest();
        let dockerfile = generate_dockerfile(&service, &manifest);

        assert!(dockerfile.contains("FROM dart:3.5"));
        assert!(dockerfile.contains("dart pub get"));
        assert!(dockerfile.contains("EXPOSE 8080"));
    }

    #[test]
    fn test_generate_python_dockerfile() {
        let service = create_test_service("api", ServiceType::Python, "python -m uvicorn main:app");
        let manifest = create_test_manifest();
        let dockerfile = generate_dockerfile(&service, &manifest);

        assert!(dockerfile.contains("FROM python:3.12-slim"));
        assert!(dockerfile.contains("pip install"));
        assert!(dockerfile.contains("EXPOSE 8080"));
    }

    #[test]
    fn test_custom_base_image() {
        let mut service = create_test_service("api", ServiceType::Node, "npm start");
        service.image = Some("node:20-bullseye".to_string());
        let manifest = create_test_manifest();
        let dockerfile = generate_dockerfile(&service, &manifest);

        assert!(dockerfile.contains("FROM node:20-bullseye"));
        assert!(!dockerfile.contains("node:22-alpine"));
    }
}
